#!/usr/bin/env bash
# terminal.sh - Terminal multiplexer and emulator configuration
# Installs: tmux, TPM (Tmux Plugin Manager)
# Configures: WezTerm (if available on Windows host)

set -euo pipefail

# Source libraries
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"
source "$SCRIPT_DIR/../lib/packages.sh"
source "$SCRIPT_DIR/../lib/symlinks.sh"

# =============================================================================
# CONFIGURATION
# =============================================================================

# Install tmux plugins automatically
TERMINAL_INSTALL_TPM="${TERMINAL_INSTALL_TPM:-true}"

# Install tmux plugins on first run
TERMINAL_INSTALL_PLUGINS="${TERMINAL_INSTALL_PLUGINS:-true}"

# =============================================================================
# TMUX INSTALLATION
# =============================================================================

install_tmux() {
    section "Installing Tmux"

    if cmd_exists tmux; then
        local version
        version="$(tmux -V | grep -oE '[0-9]+\.[0-9]+[a-z]?')"
        log_success "Tmux already installed (version $version)"
    else
        pkg_install tmux
        log_success "Tmux installed"
    fi
}

# =============================================================================
# TPM (TMUX PLUGIN MANAGER)
# =============================================================================

install_tpm() {
    if [[ "$TERMINAL_INSTALL_TPM" != "true" ]]; then
        log_skip "TPM installation disabled"
        return 0
    fi

    section "Installing TPM (Tmux Plugin Manager)"

    local tpm_dir="$HOME/.tmux/plugins/tpm"

    if [[ -d "$tpm_dir" ]]; then
        log_skip "TPM already installed"
    else
        log_info "Installing TPM..."
        git clone --depth=1 https://github.com/tmux-plugins/tpm "$tpm_dir"
        log_success "TPM installed"
    fi
}

install_tmux_plugins() {
    if [[ "$TERMINAL_INSTALL_PLUGINS" != "true" ]]; then
        log_skip "Tmux plugin installation disabled"
        return 0
    fi

    local tpm_dir="$HOME/.tmux/plugins/tpm"

    if [[ ! -d "$tpm_dir" ]]; then
        log_warn "TPM not installed, skipping plugin installation"
        return 0
    fi

    log_info "Installing tmux plugins..."

    # Source tmux config to get plugin list, then install
    if [[ -f "$HOME/.tmux.conf" ]]; then
        # Run TPM install script
        "$tpm_dir/scripts/install_plugins.sh" || true
        log_success "Tmux plugins installed"
    else
        log_warn "No .tmux.conf found, skipping plugin installation"
    fi
}

# =============================================================================
# TMUX CONFIGURATION
# =============================================================================

link_tmux_config() {
    section "Linking Tmux Configuration"

    local config_dir="$BOOTSTRAP_DIR/configs/tmux"

    if [[ ! -d "$config_dir" ]]; then
        log_error "Tmux configs not found at $config_dir"
        return 1
    fi

    safe_symlink "$config_dir/.tmux.conf" "$HOME/.tmux.conf"
    log_success "Tmux configuration linked"
}

# =============================================================================
# WEZTERM CONFIGURATION
# =============================================================================

link_wezterm_config() {
    section "Linking WezTerm Configuration"

    local config_dir="$BOOTSTRAP_DIR/configs/wezterm"

    if [[ ! -d "$config_dir" ]]; then
        log_warn "WezTerm configs not found at $config_dir"
        return 0
    fi

    # WezTerm config location depends on OS
    if is_macos; then
        safe_symlink "$config_dir/.wezterm.lua" "$HOME/.wezterm.lua"
    elif [[ "$IS_WSL" == "1" ]]; then
        # For WSL, we link to WSL home
        safe_symlink "$config_dir/.wezterm.lua" "$HOME/.wezterm.lua"

        # Create Windows config that loads from WSL
        local win_home
        win_home="$(wslpath "$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r')" 2>/dev/null || echo "")"
        if [[ -n "$win_home" && -d "$win_home" ]]; then
            log_info "Windows home detected: $win_home"

            # Get WSL distro name for the path
            local wsl_distro
            wsl_distro="$(grep -oP '(?<=^ID=).+' /etc/os-release 2>/dev/null | tr '[:lower:]' '[:upper:]' || echo "Ubuntu")"
            # Capitalize first letter
            wsl_distro="$(echo "$wsl_distro" | sed 's/./\U&/')"

            local wsl_config_path="//wsl\$/$wsl_distro$config_dir/.wezterm.lua"

            # Create Windows loader config
            cat > "$win_home/.wezterm.lua" << WEZEOF
-- WezTerm config loader for WSL
-- Auto-generated by system-configs bootstrap
-- This file loads the actual config from WSL for easy sync

local wsl_config_path = "$wsl_config_path"

-- Try to load from WSL path
local ok, result = pcall(dofile, wsl_config_path)
if ok then
    return result
end

-- Fallback: basic config if WSL path fails
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.default_domain = 'WSL:$wsl_distro'
config.font = wezterm.font('JetBrains Mono')
config.font_size = 11.0
config.color_scheme = 'Catppuccin Mocha'

return config
WEZEOF
            log_success "Created Windows WezTerm config at $win_home/.wezterm.lua"
            log_info "Windows config auto-loads from WSL path"
        fi
    else
        safe_symlink "$config_dir/.wezterm.lua" "$HOME/.wezterm.lua"
    fi

    # Install sysinfo daemon for status bar (Linux/WSL only)
    if is_linux || [[ "$IS_WSL" == "1" ]]; then
        install_sysinfo_daemon
    fi

    log_success "WezTerm configuration linked"
}

install_sysinfo_daemon() {
    local daemon_dir="$BOOTSTRAP_DIR/configs/wezterm/sysinfo-daemon"

    if [[ ! -d "$daemon_dir" ]]; then
        log_skip "Sysinfo daemon not found"
        return 0
    fi

    # Install the daemon script
    ensure_dir "$HOME/.local/bin"
    if [[ -f "$daemon_dir/sysinfo-daemon.sh" ]]; then
        safe_symlink "$daemon_dir/sysinfo-daemon.sh" "$HOME/.local/bin/sysinfo-daemon"
        chmod +x "$HOME/.local/bin/sysinfo-daemon"
    fi

    # Install systemd user service if available
    if [[ -f "$daemon_dir/sysinfo-daemon.service" ]]; then
        ensure_dir "$HOME/.config/systemd/user"
        safe_symlink "$daemon_dir/sysinfo-daemon.service" "$HOME/.config/systemd/user/sysinfo-daemon.service"

        # Enable and start the service
        if cmd_exists systemctl; then
            systemctl --user daemon-reload
            systemctl --user enable sysinfo-daemon.service 2>/dev/null || true
            systemctl --user start sysinfo-daemon.service 2>/dev/null || true
            log_success "Sysinfo daemon service enabled"
        fi
    fi
}

# =============================================================================
# ADDITIONAL TERMINAL TOOLS
# =============================================================================

install_terminal_tools() {
    section "Installing Terminal Tools"

    # xclip for clipboard support in tmux
    if is_linux && [[ "$IS_WSL" != "1" ]]; then
        pkg_install xclip
    fi

    # Install dependencies for tmux plugins
    pkg_install bash  # Ensure bash is available for scripts
}

# =============================================================================
# MAIN
# =============================================================================

install_terminal() {
    install_tmux
    install_tpm
    link_tmux_config
    install_tmux_plugins
    link_wezterm_config
    install_terminal_tools
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    install_terminal
fi
